### ISSUE TITLE
'Thread' object has no attribute 'isAlive'

### ISSUE THREAD

**Issue by Dankongithub** [Gowixx/indigo-selfbot#1]
Idek it worked the first time I ran it.

**Comment by Dankongithub** [comment]
a fix is to restart ur computer every time but still is a bug ig

**Comment by Gowixx** [comment]
This doesn't even use threads.

**Comment by Dankongithub** [comment]
nvm, Linux is just gay like that

**Comment by Gowixx** [comment]
linux moment
